# Generated by Django 4.2.5 on 2023-10-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="stripeid_subscription_id",
            new_name="stripe_subscription_id",
        ),
    ]
